services:
  database_cassandra:
    container_name: cassandra
    image: cassandra:latest
    environment:
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    ports:
      - '9042:9042'
    volumes:
      - cassandra_data:/var/lib/cassandra
    expose:
      - '9042'
    networks:
      - cassandra_network


  database_postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    ports:
      - '5432:5432'
    volumes:
      - ./init-users.sh:/docker-entrypoint-initdb.d/init-users.sh
      - pgdata:/var/lib/postgresql/data
    expose:
      - '5432'
    networks:
      - cassandra_network


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "13228:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database_postgres
    networks:
      - cassandra_network


  backend:
    container_name: 'backend-blps'
    image: 'lunghr/blps-2:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      database_cassandra:
        condition: service_healthy
      database_postgres:
        condition: service_healthy
    environment:
      SPRING_CASSANDRA_CONTACT_POINTS: ${SPRING_CASSANDRA_CONTACT_POINTS}
      SPRING_CASSANDRA_PORT: ${SPRING_CASSANDRA_PORT}
      SPRING_CASSANDRA_LOCAL_DATACENTER: ${SPRING_CASSANDRA_LOCAL_DATACENTER}
      DB_URL: ${DB_DOCKER_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - cassandra_network

networks:
  cassandra_network:
    driver: bridge

volumes:
  cassandra_data: { }
  pgdata: { }